name: Build and Release Binaries
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        arch: [amd64, arm64, arm/v7]
    steps:
      - uses: actions/checkout@v4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Build
        run: |
          docker buildx build --platform linux/${{ matrix.arch }} -t builder .
          docker create --name temp builder
          docker cp temp:/output/mpd ./mpd-${{ matrix.arch }}
          docker cp temp:/output/mpc ./mpc-${{ matrix.arch }}
      - uses: actions/upload-artifact@v4
        with:
          name: bin-${{ matrix.arch }}
          path: |
            mpd-*
            mpc-*
